VERSION.MK.MASTER = version.mk
VERSION.MK.MASTER.DIR = ..
VERSION.MK.INCLUDE = toolkit.version.mk

include $(VERSION.MK.INCLUDE)

NAME    = cuda-toolkit$(TOOLKIT_SHORT)
VERSION = $(VERSION_TOOLKIT)
RELEASE = 0

DISTDIR = distro

TOOLKIT_ARCH   = linux
TOOLKIT_SUFFIX = run
TOOLKIT_DISTRO = cuda_$(VERSION)_$(TOOLKIT_ARCH).$(TOOLKIT_SUFFIX)

