#!/bin/bash

# default log file
LOG=/var/log/nvidia-installer.log

# device driver installer
DRIVER=/opt/cuda/driver/nvidia-devdriver.run

# instructs the installer 
# - to not attempt to access the network.
# - be silent
# - do not check if nouveau kernel driver is in use.
OPT="--no-network -s -z"

# These options are run on frontend only where there is no GPU, X server is running
# and Nouveau kernel driver us loaded by default. The following options
# alow for installing libraries and include files needed for compiling samples.
# - do not install the kernel module, and do not remove any existing kernel modules.
# - do not abort the installation if nvidia-installer detects that an X server is running.
# - do not check if nouveau kernel driver is in use.
SERVEROPT="--no-kernel-module --no-x-check -z"

# check for nvidia devices, if present reset SERVEROPT to empty
NVIDIAHW=`/sbin/lspci -d 10de: | wc -l`
if [ $NVIDIAHW -gt 0 ] ; then
    SERVEROPT=
fi

echo "Installing driver with: $DRIVER $OPT $SERVEROPT"
$DRIVER $OPT $KERNOPT $SERVEROPT
echo "See installation details in $LOG"
