#!/bin/bash

/sbin/modprobe nvidia

if [ "$?" -eq 0 ]; then

    # Count the number of NVIDIA controllers found.
    N3D=`/sbin/lspci | grep -i NVIDIA | grep "3D controller" | wc -l`
    NVGA=`/sbin/lspci | grep -i NVIDIA | grep "VGA compatible controller" | wc -l`

    N=`expr $N3D + $NVGA - 1`
    for i in `seq 0 $N`; do
        /bin/mknod -m 666 /dev/nvidia$i c 195 $i;
    done

    /bin/mknod -m 666 /dev/nvidiactl c 195 255

    # Start nvidia-smi in a loop on Tesla systems.  We use the heuristic that the
    # output of nvidia-smi is very short (~5 lines) on non-Tesla systems.
    /usr/bin/pkill nvidia-smi
    N=`/usr/bin/nvidia-smi --filename=/dev/stdout 2>/dev/null | tail -n 1`
    if [ "$N" > 10 ]; then
        /usr/bin/nvidia-smi -l -i 60 --filename=/dev/stdout &> /dev/null &
    fi

else
  exit 1
fi
